// ─── Question Bank — 10 Domains ───────────────────────────────────────────────
export const questionBank = [

  // ── Software Engineer ──────────────────────────────────────────────────────
  { id: 'se-1', role: 'software-engineer', category: 'technical', difficulty: 'medium',
    question: 'Explain the difference between a process and a thread. When would you use one over the other?',
    expectedPoints: ['memory sharing', 'context switching', 'concurrency', 'OS scheduling'],
    keywords: ['process', 'thread', 'concurrency', 'memory', 'synchronization'] },
  { id: 'se-2', role: 'software-engineer', category: 'technical', difficulty: 'hard',
    question: 'Walk me through designing a rate limiter for a high-traffic API. What are the trade-offs?',
    expectedPoints: ['token bucket', 'sliding window', 'redis', 'distributed systems', 'latency'],
    keywords: ['rate limit', 'redis', 'distributed', 'token bucket', 'api'] },
  { id: 'se-3', role: 'software-engineer', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you had to refactor a large codebase under tight deadlines.',
    expectedPoints: ['planning', 'testing', 'team coordination', 'risk management'],
    keywords: ['refactor', 'deadline', 'testing', 'technical debt', 'team'] },
  { id: 'se-4', role: 'software-engineer', category: 'technical', difficulty: 'easy',
    question: 'What is Big O notation and why does it matter in software engineering?',
    expectedPoints: ['time complexity', 'space complexity', 'scalability', 'examples'],
    keywords: ['big o', 'complexity', 'algorithm', 'performance', 'scalability'] },
  { id: 'se-5', role: 'software-engineer', category: 'technical', difficulty: 'hard',
    question: 'How would you design a distributed key-value store like Redis?',
    expectedPoints: ['consistent hashing', 'replication', 'persistence', 'CAP theorem'],
    keywords: ['distributed', 'key-value', 'hashing', 'replication', 'cap theorem'] },
  { id: 'se-6', role: 'software-engineer', category: 'behavioral', difficulty: 'medium',
    question: 'Describe a situation where you disagreed with a technical decision made by your team lead.',
    expectedPoints: ['communication', 'data-backed argument', 'resolution', 'outcome'],
    keywords: ['disagreement', 'communication', 'leadership', 'technical decision'] },

  // ── Data Science ───────────────────────────────────────────────────────────
  { id: 'ds-1', role: 'data-scientist', category: 'technical', difficulty: 'medium',
    question: 'Explain the bias-variance tradeoff and how it influences model selection.',
    expectedPoints: ['underfitting', 'overfitting', 'regularization', 'cross-validation'],
    keywords: ['bias', 'variance', 'overfitting', 'regularization', 'cross-validation'] },
  { id: 'ds-2', role: 'data-scientist', category: 'technical', difficulty: 'hard',
    question: 'How would you handle class imbalance in a fraud detection dataset?',
    expectedPoints: ['SMOTE', 'undersampling', 'class weights', 'precision-recall', 'threshold tuning'],
    keywords: ['imbalance', 'SMOTE', 'sampling', 'fraud', 'precision', 'recall'] },
  { id: 'ds-3', role: 'data-scientist', category: 'behavioral', difficulty: 'medium',
    question: 'Walk me through a data science project you led from problem definition to deployment.',
    expectedPoints: ['problem framing', 'EDA', 'modeling', 'evaluation', 'deployment'],
    keywords: ['project', 'EDA', 'model', 'deployment', 'stakeholders', 'impact'] },
  { id: 'ds-4', role: 'data-scientist', category: 'technical', difficulty: 'easy',
    question: 'What is the difference between supervised and unsupervised learning? Give examples.',
    expectedPoints: ['labeled data', 'clustering', 'regression', 'classification', 'k-means'],
    keywords: ['supervised', 'unsupervised', 'clustering', 'regression', 'labels'] },
  { id: 'ds-5', role: 'data-scientist', category: 'technical', difficulty: 'hard',
    question: 'Describe how gradient boosting works and how it differs from random forests.',
    expectedPoints: ['sequential trees', 'residuals', 'learning rate', 'bagging vs boosting'],
    keywords: ['gradient boosting', 'XGBoost', 'random forest', 'bagging', 'ensemble'] },

  // ── Product Manager ────────────────────────────────────────────────────────
  { id: 'pm-1', role: 'product-manager', category: 'behavioral', difficulty: 'medium',
    question: 'How do you prioritize features when you have limited engineering resources?',
    expectedPoints: ['impact vs effort', 'RICE framework', 'stakeholder alignment', 'data-driven'],
    keywords: ['prioritization', 'RICE', 'roadmap', 'stakeholders', 'tradeoffs'] },
  { id: 'pm-2', role: 'product-manager', category: 'case', difficulty: 'hard',
    question: 'Design a notification system for a ride-sharing app. What metrics would you track?',
    expectedPoints: ['user segmentation', 'opt-in rates', 'CTR', 'A/B testing', 'fatigue'],
    keywords: ['notification', 'metrics', 'AB test', 'CTR', 'user experience'] },
  { id: 'pm-3', role: 'product-manager', category: 'behavioral', difficulty: 'easy',
    question: 'Tell me about a product you love. What would you improve and why?',
    expectedPoints: ['user empathy', 'problem identification', 'prioritization rationale'],
    keywords: ['product', 'improvement', 'user', 'design', 'feedback'] },
  { id: 'pm-4', role: 'product-manager', category: 'case', difficulty: 'hard',
    question: 'How would you decide whether to build a new AI feature or improve an existing core feature?',
    expectedPoints: ['user research', 'competitive analysis', 'ROI', 'technical feasibility'],
    keywords: ['AI feature', 'tradeoff', 'user research', 'ROI', 'competitive'] },

  // ── HR / General ───────────────────────────────────────────────────────────
  { id: 'hr-1', role: 'hr-general', category: 'behavioral', difficulty: 'easy',
    question: 'Tell me about yourself and your professional journey so far.',
    expectedPoints: ['career arc', 'key achievements', 'motivation', 'why this role'],
    keywords: ['background', 'experience', 'career', 'achievement', 'goal'] },
  { id: 'hr-2', role: 'hr-general', category: 'behavioral', difficulty: 'medium',
    question: 'Describe a conflict you had with a coworker and how you resolved it.',
    expectedPoints: ['empathy', 'communication', 'resolution process', 'outcome', 'learning'],
    keywords: ['conflict', 'resolution', 'communication', 'teamwork', 'empathy'] },
  { id: 'hr-3', role: 'hr-general', category: 'behavioral', difficulty: 'medium',
    question: 'Where do you see yourself in 5 years?',
    expectedPoints: ['growth mindset', 'realistic goals', 'alignment with company'],
    keywords: ['goals', 'growth', 'leadership', 'career path', 'vision'] },
  { id: 'hr-4', role: 'hr-general', category: 'behavioral', difficulty: 'hard',
    question: 'Tell me about a time you had to deliver bad news to a stakeholder.',
    expectedPoints: ['preparation', 'empathy', 'clear communication', 'solution-oriented'],
    keywords: ['bad news', 'stakeholder', 'communication', 'empathy', 'solution'] },

  // ── Finance ────────────────────────────────────────────────────────────────
  { id: 'fin-1', role: 'finance', category: 'technical', difficulty: 'medium',
    question: 'Walk me through a DCF valuation. What are the key assumptions you make?',
    expectedPoints: ['free cash flow', 'discount rate', 'WACC', 'terminal value', 'sensitivity'],
    keywords: ['DCF', 'valuation', 'WACC', 'cash flow', 'terminal value'] },
  { id: 'fin-2', role: 'finance', category: 'technical', difficulty: 'hard',
    question: 'How would you assess the risk of a leveraged buyout?',
    expectedPoints: ['debt service coverage', 'IRR', 'exit multiples', 'market risk'],
    keywords: ['LBO', 'leverage', 'debt', 'risk', 'exit', 'IRR'] },
  { id: 'fin-3', role: 'finance', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a financial model you built and how it influenced a business decision.',
    expectedPoints: ['model structure', 'key drivers', 'scenario analysis', 'stakeholder influence'],
    keywords: ['financial model', 'excel', 'scenario', 'decision', 'stakeholder'] },

  // ── DevOps / Cloud ─────────────────────────────────────────────────────────
  { id: 'dops-1', role: 'devops', category: 'technical', difficulty: 'medium',
    question: 'Explain the difference between blue-green and canary deployments.',
    expectedPoints: ['risk reduction', 'rollback strategy', 'traffic splitting', 'monitoring'],
    keywords: ['blue-green', 'canary', 'deployment', 'rollback', 'traffic'] },
  { id: 'dops-2', role: 'devops', category: 'technical', difficulty: 'hard',
    question: 'How would you design a CI/CD pipeline for a microservices architecture?',
    expectedPoints: ['containerization', 'orchestration', 'testing stages', 'artifact registry'],
    keywords: ['CI/CD', 'Docker', 'Kubernetes', 'pipeline', 'microservices'] },
  { id: 'dops-3', role: 'devops', category: 'behavioral', difficulty: 'medium',
    question: 'Describe a major production outage you handled. How did you triage and resolve it?',
    expectedPoints: ['incident response', 'communication', 'root cause analysis', 'postmortem'],
    keywords: ['outage', 'incident', 'triage', 'root cause', 'postmortem'] },

  // ── Machine Learning ───────────────────────────────────────────────────────
  { id: 'ml-1', role: 'machine-learning', category: 'technical', difficulty: 'hard',
    question: 'How does the attention mechanism in transformers work?',
    expectedPoints: ['query key value', 'scaled dot product', 'multi-head', 'positional encoding'],
    keywords: ['attention', 'transformer', 'query', 'key', 'value', 'BERT', 'GPT'] },
  { id: 'ml-2', role: 'machine-learning', category: 'technical', difficulty: 'medium',
    question: 'Explain how you would evaluate a recommendation system in production.',
    expectedPoints: ['offline metrics', 'online A/B test', 'CTR', 'coverage', 'diversity'],
    keywords: ['recommendation', 'evaluation', 'AB test', 'metrics', 'CTR'] },
  { id: 'ml-3', role: 'machine-learning', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a machine learning model you shipped. What challenges did you face in production?',
    expectedPoints: ['data drift', 'latency', 'monitoring', 'retraining', 'impact'],
    keywords: ['production', 'drift', 'monitoring', 'deployment', 'MLOps'] },

  // ── Marketing ──────────────────────────────────────────────────────────────
  { id: 'mkt-1', role: 'marketing', category: 'behavioral', difficulty: 'medium',
    question: 'Walk me through a campaign you planned and its results.',
    expectedPoints: ['objective', 'target audience', 'channels', 'KPIs', 'results'],
    keywords: ['campaign', 'KPI', 'audience', 'channels', 'ROI', 'conversion'] },
  { id: 'mkt-2', role: 'marketing', category: 'case', difficulty: 'hard',
    question: 'How would you grow monthly active users by 30% in 6 months for a B2C app?',
    expectedPoints: ['acquisition', 'retention', 'referral', 'paid vs organic', 'channels'],
    keywords: ['growth', 'MAU', 'acquisition', 'retention', 'channel', 'funnel'] },

  // ── Cybersecurity ──────────────────────────────────────────────────────────
  { id: 'sec-1', role: 'cybersecurity', category: 'technical', difficulty: 'medium',
    question: 'What is the difference between symmetric and asymmetric encryption? When do you use each?',
    expectedPoints: ['key distribution', 'performance', 'AES vs RSA', 'TLS', 'hybrid approach'],
    keywords: ['encryption', 'symmetric', 'asymmetric', 'AES', 'RSA', 'TLS'] },
  { id: 'sec-2', role: 'cybersecurity', category: 'behavioral', difficulty: 'hard',
    question: 'Tell me about a security incident or vulnerability you discovered and remediated.',
    expectedPoints: ['detection', 'impact assessment', 'remediation steps', 'disclosure policy'],
    keywords: ['vulnerability', 'incident', 'CVE', 'patch', 'remediation', 'disclosure'] },

  // ── Design / UX ────────────────────────────────────────────────────────────
  { id: 'ux-1', role: 'design', category: 'behavioral', difficulty: 'medium',
    question: 'Walk me through your design process for a complex feature from discovery to delivery.',
    expectedPoints: ['research', 'ideation', 'wireframes', 'prototyping', 'testing', 'iteration'],
    keywords: ['design process', 'research', 'prototype', 'usability test', 'iteration'] },
  { id: 'ux-2', role: 'design', category: 'case', difficulty: 'hard',
    question: 'How would you redesign the checkout flow of an e-commerce app to reduce cart abandonment?',
    expectedPoints: ['friction reduction', 'trust signals', 'progress indicator', 'guest checkout'],
    keywords: ['checkout', 'cart abandonment', 'UX', 'friction', 'conversion'] },

  // Expanded stabilization bank
  { id: 'se-7', role: 'software-engineer', category: 'technical', difficulty: 'easy',
    question: 'How would you debug a production bug that you cannot reproduce locally?',
    expectedPoints: ['logs', 'metrics', 'reproduction steps', 'feature flags', 'rollback'],
    keywords: ['debugging', 'logs', 'metrics', 'production', 'rollback'] },
  { id: 'se-8', role: 'software-engineer', category: 'technical', difficulty: 'medium',
    question: 'Explain how you would design database indexes for a slow search endpoint.',
    expectedPoints: ['query pattern', 'cardinality', 'compound index', 'explain plan', 'write cost'],
    keywords: ['index', 'query', 'database', 'explain', 'performance'] },
  { id: 'se-9', role: 'software-engineer', category: 'technical', difficulty: 'medium',
    question: 'What are promises in JavaScript, and how do async and await improve readability?',
    expectedPoints: ['asynchronous flow', 'resolve reject', 'error handling', 'await', 'control flow'],
    keywords: ['promise', 'async', 'await', 'javascript', 'error'] },
  { id: 'se-10', role: 'software-engineer', category: 'technical', difficulty: 'hard',
    question: 'How would you make a service idempotent when clients may retry the same request?',
    expectedPoints: ['idempotency key', 'deduplication', 'transactions', 'race conditions', 'storage'],
    keywords: ['idempotent', 'retry', 'dedupe', 'transaction', 'race'] },
  { id: 'se-11', role: 'software-engineer', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you improved code quality without slowing down delivery.',
    expectedPoints: ['incremental refactor', 'tests', 'team buy-in', 'business impact'],
    keywords: ['quality', 'refactor', 'tests', 'delivery', 'impact'] },
  { id: 'se-12', role: 'software-engineer', category: 'technical', difficulty: 'hard',
    question: 'Design a notification delivery service that supports retries, deduplication, and user preferences.',
    expectedPoints: ['queue', 'retry policy', 'deduplication', 'preferences', 'observability'],
    keywords: ['notification', 'queue', 'retry', 'deduplication', 'preferences'] },

  { id: 'ds-6', role: 'data-scientist', category: 'technical', difficulty: 'easy',
    question: 'How would you explain precision and recall to a non-technical stakeholder?',
    expectedPoints: ['false positives', 'false negatives', 'business tradeoff', 'examples'],
    keywords: ['precision', 'recall', 'false positive', 'false negative', 'stakeholder'] },
  { id: 'ds-7', role: 'data-scientist', category: 'technical', difficulty: 'medium',
    question: 'What checks would you run before trusting a new dataset for model training?',
    expectedPoints: ['missing values', 'outliers', 'schema drift', 'label quality', 'leakage'],
    keywords: ['data quality', 'missing', 'outlier', 'leakage', 'schema'] },
  { id: 'ds-8', role: 'data-scientist', category: 'case', difficulty: 'medium',
    question: 'A product metric dropped suddenly after a release. How would you investigate it?',
    expectedPoints: ['metric definition', 'segmentation', 'experiment logs', 'release impact', 'root cause'],
    keywords: ['metric', 'segmentation', 'release', 'experiment', 'root cause'] },
  { id: 'ds-9', role: 'data-scientist', category: 'technical', difficulty: 'hard',
    question: 'How would you detect and respond to data drift after deploying a model?',
    expectedPoints: ['monitoring', 'feature distribution', 'performance decay', 'alerts', 'retraining'],
    keywords: ['data drift', 'monitoring', 'distribution', 'retraining', 'alerts'] },
  { id: 'ds-10', role: 'data-scientist', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time your analysis changed a stakeholder decision.',
    expectedPoints: ['business question', 'method', 'communication', 'recommendation', 'impact'],
    keywords: ['analysis', 'stakeholder', 'decision', 'recommendation', 'impact'] },

  { id: 'pm-5', role: 'product-manager', category: 'case', difficulty: 'medium',
    question: 'How would you define success metrics for a new onboarding flow?',
    expectedPoints: ['activation', 'conversion funnel', 'retention', 'qualitative feedback', 'guardrail metrics'],
    keywords: ['onboarding', 'activation', 'retention', 'funnel', 'metrics'] },
  { id: 'pm-6', role: 'product-manager', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you said no to an important stakeholder request.',
    expectedPoints: ['prioritization', 'evidence', 'communication', 'tradeoff', 'relationship'],
    keywords: ['stakeholder', 'prioritization', 'tradeoff', 'communication', 'roadmap'] },
  { id: 'pm-7', role: 'product-manager', category: 'case', difficulty: 'hard',
    question: 'A feature has high usage but low retention impact. How would you decide what to do next?',
    expectedPoints: ['cohort analysis', 'user intent', 'retention metric', 'opportunity cost', 'experimentation'],
    keywords: ['retention', 'usage', 'cohort', 'experiment', 'opportunity cost'] },
  { id: 'pm-8', role: 'product-manager', category: 'case', difficulty: 'easy',
    question: 'How would you gather user feedback before building a feature?',
    expectedPoints: ['interviews', 'surveys', 'analytics', 'prototype testing', 'problem validation'],
    keywords: ['user feedback', 'interview', 'survey', 'prototype', 'validation'] },
  { id: 'pm-9', role: 'product-manager', category: 'technical', difficulty: 'medium',
    question: 'How do you work with engineers when technical debt competes with roadmap features?',
    expectedPoints: ['risk framing', 'customer impact', 'capacity allocation', 'sequencing', 'shared decision'],
    keywords: ['technical debt', 'roadmap', 'engineering', 'risk', 'sequencing'] },
  { id: 'pm-10', role: 'product-manager', category: 'behavioral', difficulty: 'hard',
    question: 'Describe a product bet that failed. What did you learn and how did you respond?',
    expectedPoints: ['hypothesis', 'evidence', 'failure signal', 'learning', 'next action'],
    keywords: ['failure', 'hypothesis', 'learning', 'iteration', 'metrics'] },

  { id: 'hr-5', role: 'hr-general', category: 'behavioral', difficulty: 'easy',
    question: 'Why are you interested in this role and company?',
    expectedPoints: ['motivation', 'role alignment', 'company research', 'career goals'],
    keywords: ['motivation', 'company', 'role', 'alignment', 'goals'] },
  { id: 'hr-6', role: 'hr-general', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you had to learn something quickly for a project.',
    expectedPoints: ['learning approach', 'resourcefulness', 'application', 'outcome'],
    keywords: ['learning', 'project', 'resourceful', 'outcome', 'adaptability'] },
  { id: 'hr-7', role: 'hr-general', category: 'behavioral', difficulty: 'medium',
    question: 'Describe a time you received difficult feedback. What changed afterward?',
    expectedPoints: ['openness', 'specific feedback', 'action plan', 'measurable improvement'],
    keywords: ['feedback', 'improvement', 'growth', 'action', 'learning'] },
  { id: 'hr-8', role: 'hr-general', category: 'behavioral', difficulty: 'hard',
    question: 'How do you handle competing deadlines from multiple stakeholders?',
    expectedPoints: ['prioritization', 'communication', 'tradeoffs', 'timeline management'],
    keywords: ['deadline', 'stakeholder', 'priority', 'communication', 'tradeoff'] },
  { id: 'hr-9', role: 'hr-general', category: 'behavioral', difficulty: 'easy',
    question: 'What is one strength you bring to a team, and what is one area you are improving?',
    expectedPoints: ['self-awareness', 'example', 'improvement plan', 'team relevance'],
    keywords: ['strength', 'weakness', 'team', 'self-awareness', 'growth'] },
  { id: 'hr-10', role: 'hr-general', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you took ownership beyond your assigned responsibilities.',
    expectedPoints: ['initiative', 'scope', 'collaboration', 'result', 'learning'],
    keywords: ['ownership', 'initiative', 'responsibility', 'result', 'collaboration'] },

  { id: 'fin-4', role: 'finance', category: 'technical', difficulty: 'easy',
    question: 'Explain the difference between revenue, gross profit, and net income.',
    expectedPoints: ['top line', 'cost of goods sold', 'operating expenses', 'profitability'],
    keywords: ['revenue', 'gross profit', 'net income', 'COGS', 'expenses'] },
  { id: 'fin-5', role: 'finance', category: 'technical', difficulty: 'medium',
    question: 'How would you analyze whether a company has healthy working capital?',
    expectedPoints: ['current assets', 'current liabilities', 'cash conversion cycle', 'inventory', 'receivables'],
    keywords: ['working capital', 'current ratio', 'inventory', 'receivables', 'cash'] },
  { id: 'fin-6', role: 'finance', category: 'case', difficulty: 'medium',
    question: 'A business unit missed its margin target. What analysis would you perform first?',
    expectedPoints: ['revenue mix', 'cost drivers', 'variance analysis', 'pricing', 'volume'],
    keywords: ['margin', 'variance', 'cost', 'pricing', 'volume'] },
  { id: 'fin-7', role: 'finance', category: 'technical', difficulty: 'hard',
    question: 'How do changes in interest rates affect valuation and capital allocation decisions?',
    expectedPoints: ['discount rate', 'cost of debt', 'WACC', 'risk appetite', 'investment hurdle'],
    keywords: ['interest rate', 'valuation', 'WACC', 'cost of capital', 'capital allocation'] },
  { id: 'fin-8', role: 'finance', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you found an error in financial reporting or forecasting.',
    expectedPoints: ['controls', 'investigation', 'correction', 'communication', 'prevention'],
    keywords: ['forecast', 'reporting', 'error', 'controls', 'communication'] },
  { id: 'fin-9', role: 'finance', category: 'technical', difficulty: 'medium',
    question: 'What are the main differences between cash flow and accounting profit?',
    expectedPoints: ['non-cash expenses', 'working capital', 'accruals', 'capital expenditure'],
    keywords: ['cash flow', 'profit', 'accrual', 'depreciation', 'capex'] },
  { id: 'fin-10', role: 'finance', category: 'case', difficulty: 'hard',
    question: 'How would you build a sensitivity table for a new market expansion decision?',
    expectedPoints: ['key assumptions', 'scenario ranges', 'drivers', 'downside case', 'decision threshold'],
    keywords: ['sensitivity', 'scenario', 'assumptions', 'market expansion', 'drivers'] },

  { id: 'dops-4', role: 'devops', category: 'technical', difficulty: 'easy',
    question: 'What problem does containerization solve, and when would you use Docker?',
    expectedPoints: ['consistent environment', 'dependencies', 'isolation', 'deployment portability'],
    keywords: ['Docker', 'container', 'dependencies', 'isolation', 'deployment'] },
  { id: 'dops-5', role: 'devops', category: 'technical', difficulty: 'medium',
    question: 'How would you monitor a web service to catch issues before users report them?',
    expectedPoints: ['metrics', 'logs', 'traces', 'alerts', 'SLOs'],
    keywords: ['monitoring', 'logs', 'metrics', 'tracing', 'alerts'] },
  { id: 'dops-6', role: 'devops', category: 'technical', difficulty: 'hard',
    question: 'Explain how you would design autoscaling for a latency-sensitive service.',
    expectedPoints: ['load metric', 'horizontal scaling', 'cooldown', 'capacity buffer', 'latency SLO'],
    keywords: ['autoscaling', 'latency', 'SLO', 'horizontal', 'capacity'] },
  { id: 'dops-7', role: 'devops', category: 'technical', difficulty: 'medium',
    question: 'What are the tradeoffs between serverless and container-based deployments?',
    expectedPoints: ['cold starts', 'operational control', 'cost model', 'scalability', 'vendor lock-in'],
    keywords: ['serverless', 'container', 'cold start', 'cost', 'scalability'] },
  { id: 'dops-8', role: 'devops', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you improved deployment reliability.',
    expectedPoints: ['failure mode', 'automation', 'testing', 'rollback', 'measured improvement'],
    keywords: ['deployment', 'reliability', 'automation', 'rollback', 'testing'] },
  { id: 'dops-9', role: 'devops', category: 'technical', difficulty: 'hard',
    question: 'How would you secure secrets across development, CI, and production environments?',
    expectedPoints: ['secret manager', 'least privilege', 'rotation', 'CI masking', 'audit logs'],
    keywords: ['secrets', 'CI', 'rotation', 'least privilege', 'audit'] },
  { id: 'dops-10', role: 'devops', category: 'case', difficulty: 'medium',
    question: 'A deployment succeeded but error rates doubled. What is your rollback and investigation plan?',
    expectedPoints: ['rollback criteria', 'logs', 'metrics', 'diff review', 'postmortem'],
    keywords: ['rollback', 'error rate', 'deployment', 'logs', 'postmortem'] },

  { id: 'ml-4', role: 'machine-learning', category: 'technical', difficulty: 'easy',
    question: 'What is overfitting, and how can you reduce it?',
    expectedPoints: ['training vs validation', 'regularization', 'more data', 'cross-validation'],
    keywords: ['overfitting', 'validation', 'regularization', 'cross-validation', 'data'] },
  { id: 'ml-5', role: 'machine-learning', category: 'technical', difficulty: 'medium',
    question: 'How would you choose between a simpler model and a more accurate but less explainable model?',
    expectedPoints: ['business risk', 'interpretability', 'performance', 'stakeholders', 'compliance'],
    keywords: ['explainability', 'accuracy', 'risk', 'stakeholder', 'model'] },
  { id: 'ml-6', role: 'machine-learning', category: 'technical', difficulty: 'hard',
    question: 'How would you design an ML pipeline from raw data ingestion to model monitoring?',
    expectedPoints: ['data validation', 'feature store', 'training', 'deployment', 'monitoring'],
    keywords: ['pipeline', 'feature store', 'training', 'deployment', 'monitoring'] },
  { id: 'ml-7', role: 'machine-learning', category: 'technical', difficulty: 'medium',
    question: 'Explain embeddings and give an example of where you would use them.',
    expectedPoints: ['vector representation', 'semantic similarity', 'retrieval', 'recommendation'],
    keywords: ['embedding', 'vector', 'semantic', 'retrieval', 'recommendation'] },
  { id: 'ml-8', role: 'machine-learning', category: 'case', difficulty: 'hard',
    question: 'How would you reduce hallucinations in an LLM-powered support assistant?',
    expectedPoints: ['retrieval grounding', 'prompt constraints', 'evaluation', 'fallbacks', 'human review'],
    keywords: ['LLM', 'hallucination', 'RAG', 'evaluation', 'fallback'] },
  { id: 'ml-9', role: 'machine-learning', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time model performance looked good offline but failed in production.',
    expectedPoints: ['offline metric gap', 'data drift', 'user behavior', 'monitoring', 'fix'],
    keywords: ['offline', 'production', 'drift', 'metric', 'monitoring'] },
  { id: 'ml-10', role: 'machine-learning', category: 'technical', difficulty: 'medium',
    question: 'What is feature leakage, and how would you detect it?',
    expectedPoints: ['future information', 'train test split', 'suspicious performance', 'feature audit'],
    keywords: ['leakage', 'feature', 'train test', 'audit', 'performance'] },

  { id: 'mkt-3', role: 'marketing', category: 'technical', difficulty: 'easy',
    question: 'How do you define a target audience for a new campaign?',
    expectedPoints: ['segmentation', 'persona', 'needs', 'channel behavior', 'research'],
    keywords: ['audience', 'segment', 'persona', 'research', 'channel'] },
  { id: 'mkt-4', role: 'marketing', category: 'case', difficulty: 'medium',
    question: 'A paid campaign has high clicks but low conversions. How would you diagnose the issue?',
    expectedPoints: ['landing page', 'audience fit', 'message mismatch', 'funnel analysis', 'tracking'],
    keywords: ['clicks', 'conversion', 'landing page', 'funnel', 'tracking'] },
  { id: 'mkt-5', role: 'marketing', category: 'technical', difficulty: 'medium',
    question: 'What metrics would you use to measure brand awareness?',
    expectedPoints: ['reach', 'share of voice', 'brand lift', 'direct traffic', 'survey'],
    keywords: ['brand', 'awareness', 'reach', 'share of voice', 'survey'] },
  { id: 'mkt-6', role: 'marketing', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a campaign that underperformed and how you adjusted it.',
    expectedPoints: ['diagnosis', 'test plan', 'creative or audience change', 'result', 'learning'],
    keywords: ['campaign', 'underperformed', 'test', 'creative', 'learning'] },
  { id: 'mkt-7', role: 'marketing', category: 'case', difficulty: 'hard',
    question: 'How would you launch a B2B SaaS product in a crowded market?',
    expectedPoints: ['positioning', 'ICP', 'channels', 'sales alignment', 'differentiation'],
    keywords: ['B2B', 'SaaS', 'positioning', 'ICP', 'differentiation'] },
  { id: 'mkt-8', role: 'marketing', category: 'technical', difficulty: 'medium',
    question: 'Explain how you would run and evaluate an A/B test for email subject lines.',
    expectedPoints: ['sample size', 'open rate', 'randomization', 'statistical confidence', 'guardrails'],
    keywords: ['A/B test', 'email', 'open rate', 'sample', 'confidence'] },
  { id: 'mkt-9', role: 'marketing', category: 'case', difficulty: 'medium',
    question: 'How would you improve retention through lifecycle marketing?',
    expectedPoints: ['user segments', 'triggered messaging', 'personalization', 'churn signals', 'measurement'],
    keywords: ['retention', 'lifecycle', 'personalization', 'churn', 'segments'] },
  { id: 'mkt-10', role: 'marketing', category: 'behavioral', difficulty: 'hard',
    question: 'Describe a time you aligned marketing, sales, and product around one growth goal.',
    expectedPoints: ['shared metric', 'stakeholder alignment', 'operating rhythm', 'tradeoffs', 'impact'],
    keywords: ['alignment', 'sales', 'product', 'growth', 'stakeholder'] },

  { id: 'sec-3', role: 'cybersecurity', category: 'technical', difficulty: 'easy',
    question: 'What is multi-factor authentication, and why is it stronger than passwords alone?',
    expectedPoints: ['factors', 'credential theft', 'phishing resistance', 'risk reduction'],
    keywords: ['MFA', 'password', 'phishing', 'authentication', 'risk'] },
  { id: 'sec-4', role: 'cybersecurity', category: 'technical', difficulty: 'medium',
    question: 'How would you investigate a suspicious login from an unusual location?',
    expectedPoints: ['logs', 'user verification', 'session revocation', 'password reset', 'timeline'],
    keywords: ['login', 'logs', 'suspicious', 'session', 'investigation'] },
  { id: 'sec-5', role: 'cybersecurity', category: 'technical', difficulty: 'hard',
    question: 'Explain threat modeling for a new payment feature.',
    expectedPoints: ['assets', 'trust boundaries', 'attack vectors', 'mitigations', 'STRIDE'],
    keywords: ['threat model', 'payment', 'STRIDE', 'mitigation', 'attack'] },
  { id: 'sec-6', role: 'cybersecurity', category: 'case', difficulty: 'medium',
    question: 'A dependency has a critical vulnerability. What is your response plan?',
    expectedPoints: ['impact assessment', 'patching', 'compensating controls', 'communication', 'verification'],
    keywords: ['dependency', 'vulnerability', 'patch', 'CVE', 'controls'] },
  { id: 'sec-7', role: 'cybersecurity', category: 'technical', difficulty: 'medium',
    question: 'What is the principle of least privilege, and how do you apply it in cloud systems?',
    expectedPoints: ['minimal access', 'roles', 'policy review', 'temporary access', 'audit'],
    keywords: ['least privilege', 'IAM', 'cloud', 'roles', 'audit'] },
  { id: 'sec-8', role: 'cybersecurity', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time you had to convince a team to prioritize a security fix.',
    expectedPoints: ['risk framing', 'business impact', 'communication', 'agreement', 'outcome'],
    keywords: ['security fix', 'risk', 'team', 'prioritize', 'communication'] },
  { id: 'sec-9', role: 'cybersecurity', category: 'technical', difficulty: 'hard',
    question: 'How would you design logging and alerting for a security operations workflow?',
    expectedPoints: ['signal quality', 'SIEM', 'correlation', 'severity', 'incident response'],
    keywords: ['SIEM', 'logging', 'alerting', 'incident', 'correlation'] },
  { id: 'sec-10', role: 'cybersecurity', category: 'technical', difficulty: 'medium',
    question: 'What is SQL injection, and what defenses would you put in place?',
    expectedPoints: ['parameterized queries', 'input validation', 'least privilege', 'testing'],
    keywords: ['SQL injection', 'parameterized', 'validation', 'database', 'defense'] },

  { id: 'ux-3', role: 'design', category: 'technical', difficulty: 'easy',
    question: 'How do you decide whether a design is accessible enough to ship?',
    expectedPoints: ['contrast', 'keyboard navigation', 'screen readers', 'WCAG', 'testing'],
    keywords: ['accessibility', 'contrast', 'keyboard', 'screen reader', 'WCAG'] },
  { id: 'ux-4', role: 'design', category: 'case', difficulty: 'medium',
    question: 'How would you improve a form with a high drop-off rate?',
    expectedPoints: ['analytics', 'field friction', 'validation', 'progressive disclosure', 'user testing'],
    keywords: ['form', 'drop-off', 'analytics', 'validation', 'testing'] },
  { id: 'ux-5', role: 'design', category: 'behavioral', difficulty: 'medium',
    question: 'Tell me about a time user research changed your design direction.',
    expectedPoints: ['research method', 'insight', 'decision change', 'stakeholder alignment', 'outcome'],
    keywords: ['research', 'insight', 'design direction', 'stakeholder', 'outcome'] },
  { id: 'ux-6', role: 'design', category: 'technical', difficulty: 'medium',
    question: 'How do you balance consistency with innovation in a design system?',
    expectedPoints: ['components', 'governance', 'exceptions', 'documentation', 'user value'],
    keywords: ['design system', 'consistency', 'components', 'governance', 'documentation'] },
  { id: 'ux-7', role: 'design', category: 'case', difficulty: 'hard',
    question: 'Design a dashboard for managers to identify team burnout risk.',
    expectedPoints: ['user needs', 'signals', 'privacy', 'information hierarchy', 'actions'],
    keywords: ['dashboard', 'burnout', 'privacy', 'hierarchy', 'manager'] },
  { id: 'ux-8', role: 'design', category: 'technical', difficulty: 'medium',
    question: 'How would you measure whether a redesign improved usability?',
    expectedPoints: ['task success', 'time on task', 'error rate', 'SUS', 'qualitative feedback'],
    keywords: ['usability', 'redesign', 'task success', 'error rate', 'feedback'] },
  { id: 'ux-9', role: 'design', category: 'behavioral', difficulty: 'hard',
    question: 'Describe a time you disagreed with product or engineering about a user experience decision.',
    expectedPoints: ['evidence', 'collaboration', 'tradeoff', 'resolution', 'user impact'],
    keywords: ['disagreement', 'product', 'engineering', 'evidence', 'user impact'] },
  { id: 'ux-10', role: 'design', category: 'case', difficulty: 'medium',
    question: 'How would you design empty states for a new analytics product?',
    expectedPoints: ['user intent', 'guidance', 'sample data', 'activation', 'tone'],
    keywords: ['empty state', 'analytics', 'guidance', 'sample data', 'activation'] }
];

// ─── Persona Profiles ─────────────────────────────────────────────────────────
export const personaProfiles = {
  'calm-senior-interviewer': {
    name: 'Dr. Sarah Chen',
    title: 'Senior Principal Engineer',
    style: 'Methodical, thorough, focuses on depth over breadth.',
    tone: 'Calm and encouraging, but expects precision.',
    intro: 'Hello! I am Dr. Sarah Chen. I will be your interviewer today. Let us begin.'
  },
  'friendly-recruiter': {
    name: 'Marcus Williams',
    title: 'Talent Acquisition Lead',
    style: 'Conversational and warm, focuses on cultural fit and potential.',
    tone: 'Energetic and supportive — wants you to succeed.',
    intro: 'Hey! Great to meet you. I am Marcus. This will be a great conversation — ready to get started?'
  },
  'strict-panelist': {
    name: 'Alexandra Petrov',
    title: 'VP of Engineering',
    style: 'Direct, demanding, minimal patience for vague answers.',
    tone: 'Businesslike and challenging — every answer must be precise.',
    intro: 'I am Alexandra. I will be direct. I expect specific answers with clear reasoning. Let us begin.'
  },
  'startup-founder': {
    name: 'Kai Okafor',
    title: 'Co-Founder & CTO',
    style: 'Fast-paced, loves first-principles thinking and execution stories.',
    tone: 'Excited and curious, looking for builders who get things done.',
    intro: 'Hey, Kai here. We move fast and I love builders. Tell me how you think. Let us go!'
  },
  'technical-mentor': {
    name: 'Maya Iyer',
    title: 'Staff Engineer and Interview Coach',
    style: 'Supportive and structured, gives light nudges while still expecting clear reasoning.',
    tone: 'Calm, patient, and confidence-building.',
    intro: 'Hello, I am Maya. I will guide the conversation with practical questions and a few helpful nudges. Let us begin.'
  },
  'senior-engineering-manager': {
    name: 'Daniel Brooks',
    title: 'Senior Engineering Manager',
    style: 'Project-focused and pragmatic, probes ownership, debugging, tradeoffs, and teamwork.',
    tone: 'Professional, direct, and outcome-oriented.',
    intro: 'Hi, I am Daniel. I will focus on how you make decisions, handle ambiguity, and deliver reliable work. Let us start.'
  },
  'strict-product-interviewer': {
    name: 'Priya Nair',
    title: 'Product Strategy Interviewer',
    style: 'Concise and time-conscious, pushes for clarity, customer impact, metrics, and decisions.',
    tone: 'Direct, analytical, and low tolerance for vague answers.',
    intro: 'I am Priya. I will keep this concise and expect crisp answers tied to user value and business impact. Let us begin.'
  }
};
